name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: openzim/docker-publish-action@v10
        with:
          registries: ghcr.io
          image-name: openzim/phet
          on-master: dev
          latest-on-tag: true
          restrict-to: openzim/phet
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
